# Generated by Django 2.1.5 on 2019-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refugee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
